// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repo/persistent/user_postgres.go
//
// Generated by this command:
//
//	mockgen -source=internal/repo/persistent/user_postgres.go -destination=internal/mocks/mock_user_repo.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks
