database:
  host: "localhost"
  user: "postgres"
  password: "postgres"
  name: "library"
  port: "5432"
  sslmode: "disable"
  timezone: "Europe/Moscow"

jwt:
  SecretKey: "какой-то-интересный-секретный-ключ"

smtp:
  host: smtp.mail.ru
  port: 465
  email: alisa_barysheva03@mail.ru
  password: aLt6DaiDvvCjaXYRCXps